### ISSUE TITLE
add macOS compatibility

### ISSUE THREAD

**Issue by Goldenstarc** [hash3liZer/WiFiBroot#15]
is it possible to implement?

**Comment by hash3liZer** [comment]
Hi, Perhaps you can help me with that. But does MAC support monitor mode? If yes, we can implement it.

**Comment by Goldenstarc** [comment]
yes,
see these
better way:
https://ss64.com/osx/tcpdump.html
and airport
https://apple.stackexchange.com/questions/272930/how-to-enable-wireless-monitoring-macbook-pro

**Comment by mogekag** [comment]
Mac seems to support monitor mode, but it seems like once cannot pu the card into monitor mode with actively sniffing for something. I was able to list the interfaces in _wifibroot.py_ by using:
`	
def list_ifaces(self):
		ifaces = []
		'''
		macos does not have this directory, instead you can check for interfaces
		with the command networksetup -listallhardwareports .
		'''
		#dev = open('/proc/net/dev', 'r')
		#data = dev.read()
		# for facecard in re.findall('[a-zA-Z0-9]+:', data):
		# 	ifaces.append(facecard.rstrip(":"))
		# dev.close()
		os.system('networksetup -listallhardwareports | grep \'Device\' | sed s/"Device: "/""/g > /tmp/iface-wifibroot.txt')
		dev = open('/tmp/iface-wifibroot.txt', 'r')
		for facecard in dev.readlines():
			ifaces.append(facecard.rstrip('\n'))
		dev.close()
		return ifaces
`
On **is_mon()** and **is_man()** I was able to replicate the behavior on linux by declaring airport built-in tool path and changing the regexp, but since one cannot actively put the interface on monitor mode and just leave it, I ended up completely bypassing this on **check_mon()**.
`_OS_AIRPORT_PATH = '/System/Library/PrivateFrameworks/Apple80211.framework/Versions/Current/Resources/airport'`
`	
def is_mon(self, iface):
		co = subprocess.Popen([_OS_AIRPORT_PATH, '-I'], stdout=subprocess.PIPE)
		data = co.communicate()[0].decode('utf-8')
		card = re.findall('op mode: [A-Za-z]+', data)
		if "monitor" in card:
			return True
		else:
			return False
`

Now, one **can** set a specific channel with airport command with `os.system(_OS_AIRPORT_PATH + " %s -c%d" % (self.iface, n))` on all hopper related functions, but I still was not able to scan for networks the same way as `airport -s`.
